const { iconsMap } = require('./iconsList.js');
const { transList } = require('./transactionsList.js');

let budgsListWithoutIcon = [
    {
        id: '26_04-1',
        category: 'Ăn uống',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 500000,
        alertThreshold: 80,
        isActive: true,
    },
    {
        id: '26_04-2',
        category: 'Đơn điện tử',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 300000,
        alertThreshold: 70,
        isActive: true,
    },
    {
        id: '26_04-3',
        category: 'Sức khỏe',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 500000,
        alertThreshold: 50,
        isActive: false,
    },
    {
        id: '26_04-4',
        category: 'Nhà ở',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 1600000,
        alertThreshold: 70,
        isActive: true,
    },
    {
        id: '26_04-5',
        category: 'Đi lại',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 1600000,
        alertThreshold: 70,
        isActive: true,
    },
    {
        id: '26_04-6',
        category: 'Giải trí',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 300000,
        alertThreshold: 70,
        isActive: true,
    },
    {
        id: '26_04-7',
        category: 'Mua sắm',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 10000,
        alertThreshold: 70,
        isActive: false,
    },
    {
        id: '26_03-1',
        category: 'Ăn uống',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 500000,
        alertThreshold: 80,
        isActive: true,
    },
    {
        id: '26_03-2',
        category: 'Đơn điện tử',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 300000,
        alertThreshold: 70,
        isActive: false,
    },
    {
        id: '26_03-3',
        category: 'Sức khỏe',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 500000,
        alertThreshold: 50,
        isActive: true,
    },
    {
        id: '26_03-4',
        category: 'Nhà ở',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 1400000,
        alertThreshold: 70,
        isActive: true,
    },
    {
        id: '26_03-5',
        category: 'Đi lại',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 560000,
        alertThreshold: 75,
        isActive: true,
    },
    {
        id: '26_03-6',
        category: 'Giải trí',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 180000,
        alertThreshold: 75,
        isActive: true,
    },
    {
        id: '26_03-7',
        category: 'Mua sắm',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 730000,
        alertThreshold: 75,
        isActive: true,
    },
    {
        id: '26_03-8',
        category: 'Chi tiêu khác',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 120000,
        alertThreshold: 75,
        isActive: true,
    },
];

let budgsList = budgsListWithoutIcon.map(item => ({
    ...item,
    categoryIcon: `http://localhost:8080/api/images/${iconsMap[item.category]}.png`,
    amountConsumed: transList.filter(i => i.category === item.category)
        .filter(i => i.date.substring(3, 5) === item.id.substring(3, 5))
        .reduce((s, i) => s + i.amount, 0),
}));

module.exports = { budgsList };
