const { iconsMap } = require('./iconsList.js');

let budgsListWithoutIcon = [
    {
        id: '26_04-1',
        category: 'Ăn uống',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 500000,
        alertThreshold: 80,
        isActive: true,
        amountConsumed: 250000,
        percentConsumed: 50,
    },
    {
        id: '26_04-2',
        category: 'Đơn điện tử',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 300000,
        alertThreshold: 70,
        isActive: true,
        amountConsumed: 150000,
        percentConsumed: 50,
    },
    {
        id: '26_04-3',
        category: 'Sức khỏe',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 500000,
        alertThreshold: 50,
        isActive: true,
        amountConsumed: 125000,
        percentConsumed: 25,
    },
    {
        id: '26_04-4',
        category: 'Nhà ở',
        month: 'Tháng 4',
        year: '2026',
        limitAmount: 1600000,
        alertThreshold: 70,
        isActive: true,
        amountConsumed: 250000,
        percentConsumed: 16,
    },
    {
        id: '26_03-1',
        category: 'Ăn uống',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 500000,
        alertThreshold: 80,
        isActive: true,
        amountConsumed: 100000,
        percentConsumed: 20,
    },
    {
        id: '26_03-2',
        category: 'Đơn điện tử',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 300000,
        alertThreshold: 70,
        isActive: false,
        amountConsumed: 30000,
        percentConsumed: 10,
    },
    {
        id: '26_03-3',
        category: 'Sức khỏe',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 500000,
        alertThreshold: 50,
        isActive: true,
        amountConsumed: 250000,
        percentConsumed: 50,
    },
    {
        id: '26_03-4',
        category: 'Nhà ở',
        month: 'Tháng 3',
        year: '2026',
        limitAmount: 600000,
        alertThreshold: 70,
        isActive: false,
        amountConsumed: 100000,
        percentConsumed: 17,
    },
];

let budgsList = budgsListWithoutIcon.map(item => ({
    ...item,
    categoryIcon: `http://localhost:8080/api/images/${iconsMap[item.category]}.png`
}));

module.exports = { budgsList };
